// <auto-generated />
namespace CodeFirstSample.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class usersDeleted : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(usersDeleted));
        
        string IMigrationMetadata.Id
        {
            get { return "201209241504135_usersDeleted"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
