//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Microsoft.Samples.SqlServer.AdventureWorksService
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AdventureWorksEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AdventureWorksEntities object using the connection string found in the 'AdventureWorksEntities' section of the application configuration file.
        /// </summary>
        public AdventureWorksEntities() : base("name=AdventureWorksEntities", "AdventureWorksEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AdventureWorksEntities object.
        /// </summary>
        public AdventureWorksEntities(string connectionString) : base(connectionString, "AdventureWorksEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AdventureWorksEntities object.
        /// </summary>
        public AdventureWorksEntities(EntityConnection connection) : base(connection, "AdventureWorksEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vManufacturingInstructions> ManufacturingInstructions
        {
            get
            {
                if ((_ManufacturingInstructions == null))
                {
                    _ManufacturingInstructions = base.CreateObjectSet<vManufacturingInstructions>("ManufacturingInstructions");
                }
                return _ManufacturingInstructions;
            }
        }
        private ObjectSet<vManufacturingInstructions> _ManufacturingInstructions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vWorkOrderRouting> WorkOrderRouting
        {
            get
            {
                if ((_WorkOrderRouting == null))
                {
                    _WorkOrderRouting = base.CreateObjectSet<vWorkOrderRouting>("WorkOrderRouting");
                }
                return _WorkOrderRouting;
            }
        }
        private ObjectSet<vWorkOrderRouting> _WorkOrderRouting;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vProductCatalog> ProductCatalog
        {
            get
            {
                if ((_ProductCatalog == null))
                {
                    _ProductCatalog = base.CreateObjectSet<vProductCatalog>("ProductCatalog");
                }
                return _ProductCatalog;
            }
        }
        private ObjectSet<vProductCatalog> _ProductCatalog;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vCompanySales> CompanySales
        {
            get
            {
                if ((_CompanySales == null))
                {
                    _CompanySales = base.CreateObjectSet<vCompanySales>("CompanySales");
                }
                return _CompanySales;
            }
        }
        private ObjectSet<vCompanySales> _CompanySales;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vTerritorySalesDrilldown> TerritorySalesDrilldown
        {
            get
            {
                if ((_TerritorySalesDrilldown == null))
                {
                    _TerritorySalesDrilldown = base.CreateObjectSet<vTerritorySalesDrilldown>("TerritorySalesDrilldown");
                }
                return _TerritorySalesDrilldown;
            }
        }
        private ObjectSet<vTerritorySalesDrilldown> _TerritorySalesDrilldown;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ManufacturingInstructions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToManufacturingInstructions(vManufacturingInstructions vManufacturingInstructions)
        {
            base.AddObject("ManufacturingInstructions", vManufacturingInstructions);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the WorkOrderRouting EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWorkOrderRouting(vWorkOrderRouting vWorkOrderRouting)
        {
            base.AddObject("WorkOrderRouting", vWorkOrderRouting);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ProductCatalog EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProductCatalog(vProductCatalog vProductCatalog)
        {
            base.AddObject("ProductCatalog", vProductCatalog);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CompanySales EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCompanySales(vCompanySales vCompanySales)
        {
            base.AddObject("CompanySales", vCompanySales);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TerritorySalesDrilldown EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTerritorySalesDrilldown(vTerritorySalesDrilldown vTerritorySalesDrilldown)
        {
            base.AddObject("TerritorySalesDrilldown", vTerritorySalesDrilldown);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AdventureWorksModel", Name="vCompanySales")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vCompanySales : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vCompanySales object.
        /// </summary>
        /// <param name="productCategory">Initial value of the ProductCategory property.</param>
        /// <param name="productSubCategory">Initial value of the ProductSubCategory property.</param>
        /// <param name="id">Initial value of the ID property.</param>
        public static vCompanySales CreatevCompanySales(global::System.String productCategory, global::System.String productSubCategory, global::System.Int64 id)
        {
            vCompanySales vCompanySales = new vCompanySales();
            vCompanySales.ProductCategory = productCategory;
            vCompanySales.ProductSubCategory = productSubCategory;
            vCompanySales.ID = id;
            return vCompanySales;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProductCategory
        {
            get
            {
                return _ProductCategory;
            }
            set
            {
                OnProductCategoryChanging(value);
                ReportPropertyChanging("ProductCategory");
                _ProductCategory = StructuralObject.SetValidValue(value, false, "ProductCategory");
                ReportPropertyChanged("ProductCategory");
                OnProductCategoryChanged();
            }
        }
        private global::System.String _ProductCategory;
        partial void OnProductCategoryChanging(global::System.String value);
        partial void OnProductCategoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProductSubCategory
        {
            get
            {
                return _ProductSubCategory;
            }
            set
            {
                OnProductSubCategoryChanging(value);
                ReportPropertyChanging("ProductSubCategory");
                _ProductSubCategory = StructuralObject.SetValidValue(value, false, "ProductSubCategory");
                ReportPropertyChanged("ProductSubCategory");
                OnProductSubCategoryChanged();
            }
        }
        private global::System.String _ProductSubCategory;
        partial void OnProductSubCategoryChanging(global::System.String value);
        partial void OnProductSubCategoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> OrderYear
        {
            get
            {
                return _OrderYear;
            }
            set
            {
                OnOrderYearChanging(value);
                ReportPropertyChanging("OrderYear");
                _OrderYear = StructuralObject.SetValidValue(value, "OrderYear");
                ReportPropertyChanged("OrderYear");
                OnOrderYearChanged();
            }
        }
        private Nullable<global::System.Int32> _OrderYear;
        partial void OnOrderYearChanging(Nullable<global::System.Int32> value);
        partial void OnOrderYearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OrderQtr
        {
            get
            {
                return _OrderQtr;
            }
            set
            {
                OnOrderQtrChanging(value);
                ReportPropertyChanging("OrderQtr");
                _OrderQtr = StructuralObject.SetValidValue(value, true, "OrderQtr");
                ReportPropertyChanged("OrderQtr");
                OnOrderQtrChanged();
            }
        }
        private global::System.String _OrderQtr;
        partial void OnOrderQtrChanging(global::System.String value);
        partial void OnOrderQtrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Sales
        {
            get
            {
                return _Sales;
            }
            set
            {
                OnSalesChanging(value);
                ReportPropertyChanging("Sales");
                _Sales = StructuralObject.SetValidValue(value, "Sales");
                ReportPropertyChanged("Sales");
                OnSalesChanged();
            }
        }
        private Nullable<global::System.Decimal> _Sales;
        partial void OnSalesChanging(Nullable<global::System.Decimal> value);
        partial void OnSalesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AdventureWorksModel", Name="vManufacturingInstructions")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vManufacturingInstructions : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vManufacturingInstructions object.
        /// </summary>
        /// <param name="productModelID">Initial value of the ProductModelID property.</param>
        /// <param name="productName">Initial value of the ProductName property.</param>
        /// <param name="id">Initial value of the ID property.</param>
        public static vManufacturingInstructions CreatevManufacturingInstructions(global::System.Int32 productModelID, global::System.String productName, global::System.Int64 id)
        {
            vManufacturingInstructions vManufacturingInstructions = new vManufacturingInstructions();
            vManufacturingInstructions.ProductModelID = productModelID;
            vManufacturingInstructions.ProductName = productName;
            vManufacturingInstructions.ID = id;
            return vManufacturingInstructions;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProductModelID
        {
            get
            {
                return _ProductModelID;
            }
            set
            {
                OnProductModelIDChanging(value);
                ReportPropertyChanging("ProductModelID");
                _ProductModelID = StructuralObject.SetValidValue(value, "ProductModelID");
                ReportPropertyChanged("ProductModelID");
                OnProductModelIDChanged();
            }
        }
        private global::System.Int32 _ProductModelID;
        partial void OnProductModelIDChanging(global::System.Int32 value);
        partial void OnProductModelIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProductName
        {
            get
            {
                return _ProductName;
            }
            set
            {
                OnProductNameChanging(value);
                ReportPropertyChanging("ProductName");
                _ProductName = StructuralObject.SetValidValue(value, false, "ProductName");
                ReportPropertyChanged("ProductName");
                OnProductNameChanged();
            }
        }
        private global::System.String _ProductName;
        partial void OnProductNameChanging(global::System.String value);
        partial void OnProductNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Instructions
        {
            get
            {
                return _Instructions;
            }
            set
            {
                OnInstructionsChanging(value);
                ReportPropertyChanging("Instructions");
                _Instructions = StructuralObject.SetValidValue(value, true, "Instructions");
                ReportPropertyChanged("Instructions");
                OnInstructionsChanged();
            }
        }
        private global::System.String _Instructions;
        partial void OnInstructionsChanging(global::System.String value);
        partial void OnInstructionsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LocationID
        {
            get
            {
                return _LocationID;
            }
            set
            {
                OnLocationIDChanging(value);
                ReportPropertyChanging("LocationID");
                _LocationID = StructuralObject.SetValidValue(value, "LocationID");
                ReportPropertyChanged("LocationID");
                OnLocationIDChanged();
            }
        }
        private Nullable<global::System.Int32> _LocationID;
        partial void OnLocationIDChanging(Nullable<global::System.Int32> value);
        partial void OnLocationIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> SetupHours
        {
            get
            {
                return _SetupHours;
            }
            set
            {
                OnSetupHoursChanging(value);
                ReportPropertyChanging("SetupHours");
                _SetupHours = StructuralObject.SetValidValue(value, "SetupHours");
                ReportPropertyChanged("SetupHours");
                OnSetupHoursChanged();
            }
        }
        private Nullable<global::System.Decimal> _SetupHours;
        partial void OnSetupHoursChanging(Nullable<global::System.Decimal> value);
        partial void OnSetupHoursChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> MachineHours
        {
            get
            {
                return _MachineHours;
            }
            set
            {
                OnMachineHoursChanging(value);
                ReportPropertyChanging("MachineHours");
                _MachineHours = StructuralObject.SetValidValue(value, "MachineHours");
                ReportPropertyChanged("MachineHours");
                OnMachineHoursChanged();
            }
        }
        private Nullable<global::System.Decimal> _MachineHours;
        partial void OnMachineHoursChanging(Nullable<global::System.Decimal> value);
        partial void OnMachineHoursChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> LaborHours
        {
            get
            {
                return _LaborHours;
            }
            set
            {
                OnLaborHoursChanging(value);
                ReportPropertyChanging("LaborHours");
                _LaborHours = StructuralObject.SetValidValue(value, "LaborHours");
                ReportPropertyChanged("LaborHours");
                OnLaborHoursChanged();
            }
        }
        private Nullable<global::System.Decimal> _LaborHours;
        partial void OnLaborHoursChanging(Nullable<global::System.Decimal> value);
        partial void OnLaborHoursChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LotSize
        {
            get
            {
                return _LotSize;
            }
            set
            {
                OnLotSizeChanging(value);
                ReportPropertyChanging("LotSize");
                _LotSize = StructuralObject.SetValidValue(value, "LotSize");
                ReportPropertyChanged("LotSize");
                OnLotSizeChanged();
            }
        }
        private Nullable<global::System.Int32> _LotSize;
        partial void OnLotSizeChanging(Nullable<global::System.Int32> value);
        partial void OnLotSizeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Step
        {
            get
            {
                return _Step;
            }
            set
            {
                OnStepChanging(value);
                ReportPropertyChanging("Step");
                _Step = StructuralObject.SetValidValue(value, true, "Step");
                ReportPropertyChanged("Step");
                OnStepChanged();
            }
        }
        private global::System.String _Step;
        partial void OnStepChanging(global::System.String value);
        partial void OnStepChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AdventureWorksModel", Name="vProductCatalog")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vProductCatalog : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vProductCatalog object.
        /// </summary>
        /// <param name="productID">Initial value of the ProductID property.</param>
        /// <param name="productNumber">Initial value of the ProductNumber property.</param>
        /// <param name="productName">Initial value of the ProductName property.</param>
        /// <param name="productModel">Initial value of the ProductModel property.</param>
        /// <param name="productCategory">Initial value of the ProductCategory property.</param>
        /// <param name="productSubcategory">Initial value of the ProductSubcategory property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="cultureID">Initial value of the CultureID property.</param>
        /// <param name="listPrice">Initial value of the ListPrice property.</param>
        /// <param name="id">Initial value of the ID property.</param>
        public static vProductCatalog CreatevProductCatalog(global::System.Int32 productID, global::System.String productNumber, global::System.String productName, global::System.String productModel, global::System.String productCategory, global::System.String productSubcategory, global::System.String description, global::System.String cultureID, global::System.Decimal listPrice, global::System.Int64 id)
        {
            vProductCatalog vProductCatalog = new vProductCatalog();
            vProductCatalog.ProductID = productID;
            vProductCatalog.ProductNumber = productNumber;
            vProductCatalog.ProductName = productName;
            vProductCatalog.ProductModel = productModel;
            vProductCatalog.ProductCategory = productCategory;
            vProductCatalog.ProductSubcategory = productSubcategory;
            vProductCatalog.Description = description;
            vProductCatalog.CultureID = cultureID;
            vProductCatalog.ListPrice = listPrice;
            vProductCatalog.ID = id;
            return vProductCatalog;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProductID
        {
            get
            {
                return _ProductID;
            }
            set
            {
                OnProductIDChanging(value);
                ReportPropertyChanging("ProductID");
                _ProductID = StructuralObject.SetValidValue(value, "ProductID");
                ReportPropertyChanged("ProductID");
                OnProductIDChanged();
            }
        }
        private global::System.Int32 _ProductID;
        partial void OnProductIDChanging(global::System.Int32 value);
        partial void OnProductIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProductNumber
        {
            get
            {
                return _ProductNumber;
            }
            set
            {
                OnProductNumberChanging(value);
                ReportPropertyChanging("ProductNumber");
                _ProductNumber = StructuralObject.SetValidValue(value, false, "ProductNumber");
                ReportPropertyChanged("ProductNumber");
                OnProductNumberChanged();
            }
        }
        private global::System.String _ProductNumber;
        partial void OnProductNumberChanging(global::System.String value);
        partial void OnProductNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProductName
        {
            get
            {
                return _ProductName;
            }
            set
            {
                OnProductNameChanging(value);
                ReportPropertyChanging("ProductName");
                _ProductName = StructuralObject.SetValidValue(value, false, "ProductName");
                ReportPropertyChanged("ProductName");
                OnProductNameChanged();
            }
        }
        private global::System.String _ProductName;
        partial void OnProductNameChanging(global::System.String value);
        partial void OnProductNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProductModel
        {
            get
            {
                return _ProductModel;
            }
            set
            {
                OnProductModelChanging(value);
                ReportPropertyChanging("ProductModel");
                _ProductModel = StructuralObject.SetValidValue(value, false, "ProductModel");
                ReportPropertyChanged("ProductModel");
                OnProductModelChanged();
            }
        }
        private global::System.String _ProductModel;
        partial void OnProductModelChanging(global::System.String value);
        partial void OnProductModelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProductCategory
        {
            get
            {
                return _ProductCategory;
            }
            set
            {
                OnProductCategoryChanging(value);
                ReportPropertyChanging("ProductCategory");
                _ProductCategory = StructuralObject.SetValidValue(value, false, "ProductCategory");
                ReportPropertyChanged("ProductCategory");
                OnProductCategoryChanged();
            }
        }
        private global::System.String _ProductCategory;
        partial void OnProductCategoryChanging(global::System.String value);
        partial void OnProductCategoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProductSubcategory
        {
            get
            {
                return _ProductSubcategory;
            }
            set
            {
                OnProductSubcategoryChanging(value);
                ReportPropertyChanging("ProductSubcategory");
                _ProductSubcategory = StructuralObject.SetValidValue(value, false, "ProductSubcategory");
                ReportPropertyChanged("ProductSubcategory");
                OnProductSubcategoryChanged();
            }
        }
        private global::System.String _ProductSubcategory;
        partial void OnProductSubcategoryChanging(global::System.String value);
        partial void OnProductSubcategoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false, "Description");
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CultureID
        {
            get
            {
                return _CultureID;
            }
            set
            {
                OnCultureIDChanging(value);
                ReportPropertyChanging("CultureID");
                _CultureID = StructuralObject.SetValidValue(value, false, "CultureID");
                ReportPropertyChanged("CultureID");
                OnCultureIDChanged();
            }
        }
        private global::System.String _CultureID;
        partial void OnCultureIDChanging(global::System.String value);
        partial void OnCultureIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Color
        {
            get
            {
                return _Color;
            }
            set
            {
                OnColorChanging(value);
                ReportPropertyChanging("Color");
                _Color = StructuralObject.SetValidValue(value, true, "Color");
                ReportPropertyChanged("Color");
                OnColorChanged();
            }
        }
        private global::System.String _Color;
        partial void OnColorChanging(global::System.String value);
        partial void OnColorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Size
        {
            get
            {
                return _Size;
            }
            set
            {
                OnSizeChanging(value);
                ReportPropertyChanging("Size");
                _Size = StructuralObject.SetValidValue(value, true, "Size");
                ReportPropertyChanged("Size");
                OnSizeChanged();
            }
        }
        private global::System.String _Size;
        partial void OnSizeChanging(global::System.String value);
        partial void OnSizeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Weight
        {
            get
            {
                return _Weight;
            }
            set
            {
                OnWeightChanging(value);
                ReportPropertyChanging("Weight");
                _Weight = StructuralObject.SetValidValue(value, "Weight");
                ReportPropertyChanged("Weight");
                OnWeightChanged();
            }
        }
        private Nullable<global::System.Decimal> _Weight;
        partial void OnWeightChanging(Nullable<global::System.Decimal> value);
        partial void OnWeightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ListPrice
        {
            get
            {
                return _ListPrice;
            }
            set
            {
                OnListPriceChanging(value);
                ReportPropertyChanging("ListPrice");
                _ListPrice = StructuralObject.SetValidValue(value, "ListPrice");
                ReportPropertyChanged("ListPrice");
                OnListPriceChanged();
            }
        }
        private global::System.Decimal _ListPrice;
        partial void OnListPriceChanging(global::System.Decimal value);
        partial void OnListPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AdventureWorksModel", Name="vTerritorySalesDrilldown")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vTerritorySalesDrilldown : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vTerritorySalesDrilldown object.
        /// </summary>
        /// <param name="territoryName">Initial value of the TerritoryName property.</param>
        /// <param name="salesPersonID">Initial value of the SalesPersonID property.</param>
        /// <param name="employeeFirstName">Initial value of the EmployeeFirstName property.</param>
        /// <param name="employeeLastName">Initial value of the EmployeeLastName property.</param>
        /// <param name="salesOrderNumber">Initial value of the SalesOrderNumber property.</param>
        /// <param name="total">Initial value of the Total property.</param>
        /// <param name="id">Initial value of the ID property.</param>
        public static vTerritorySalesDrilldown CreatevTerritorySalesDrilldown(global::System.String territoryName, global::System.Int32 salesPersonID, global::System.String employeeFirstName, global::System.String employeeLastName, global::System.String salesOrderNumber, global::System.Decimal total, global::System.Int64 id)
        {
            vTerritorySalesDrilldown vTerritorySalesDrilldown = new vTerritorySalesDrilldown();
            vTerritorySalesDrilldown.TerritoryName = territoryName;
            vTerritorySalesDrilldown.SalesPersonID = salesPersonID;
            vTerritorySalesDrilldown.EmployeeFirstName = employeeFirstName;
            vTerritorySalesDrilldown.EmployeeLastName = employeeLastName;
            vTerritorySalesDrilldown.SalesOrderNumber = salesOrderNumber;
            vTerritorySalesDrilldown.Total = total;
            vTerritorySalesDrilldown.ID = id;
            return vTerritorySalesDrilldown;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TerritoryName
        {
            get
            {
                return _TerritoryName;
            }
            set
            {
                OnTerritoryNameChanging(value);
                ReportPropertyChanging("TerritoryName");
                _TerritoryName = StructuralObject.SetValidValue(value, false, "TerritoryName");
                ReportPropertyChanged("TerritoryName");
                OnTerritoryNameChanged();
            }
        }
        private global::System.String _TerritoryName;
        partial void OnTerritoryNameChanging(global::System.String value);
        partial void OnTerritoryNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SalesPersonID
        {
            get
            {
                return _SalesPersonID;
            }
            set
            {
                OnSalesPersonIDChanging(value);
                ReportPropertyChanging("SalesPersonID");
                _SalesPersonID = StructuralObject.SetValidValue(value, "SalesPersonID");
                ReportPropertyChanged("SalesPersonID");
                OnSalesPersonIDChanged();
            }
        }
        private global::System.Int32 _SalesPersonID;
        partial void OnSalesPersonIDChanging(global::System.Int32 value);
        partial void OnSalesPersonIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EmployeeFirstName
        {
            get
            {
                return _EmployeeFirstName;
            }
            set
            {
                OnEmployeeFirstNameChanging(value);
                ReportPropertyChanging("EmployeeFirstName");
                _EmployeeFirstName = StructuralObject.SetValidValue(value, false, "EmployeeFirstName");
                ReportPropertyChanged("EmployeeFirstName");
                OnEmployeeFirstNameChanged();
            }
        }
        private global::System.String _EmployeeFirstName;
        partial void OnEmployeeFirstNameChanging(global::System.String value);
        partial void OnEmployeeFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EmployeeLastName
        {
            get
            {
                return _EmployeeLastName;
            }
            set
            {
                OnEmployeeLastNameChanging(value);
                ReportPropertyChanging("EmployeeLastName");
                _EmployeeLastName = StructuralObject.SetValidValue(value, false, "EmployeeLastName");
                ReportPropertyChanged("EmployeeLastName");
                OnEmployeeLastNameChanged();
            }
        }
        private global::System.String _EmployeeLastName;
        partial void OnEmployeeLastNameChanging(global::System.String value);
        partial void OnEmployeeLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SalesOrderNumber
        {
            get
            {
                return _SalesOrderNumber;
            }
            set
            {
                OnSalesOrderNumberChanging(value);
                ReportPropertyChanging("SalesOrderNumber");
                _SalesOrderNumber = StructuralObject.SetValidValue(value, false, "SalesOrderNumber");
                ReportPropertyChanged("SalesOrderNumber");
                OnSalesOrderNumberChanged();
            }
        }
        private global::System.String _SalesOrderNumber;
        partial void OnSalesOrderNumberChanging(global::System.String value);
        partial void OnSalesOrderNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Total
        {
            get
            {
                return _Total;
            }
            set
            {
                OnTotalChanging(value);
                ReportPropertyChanging("Total");
                _Total = StructuralObject.SetValidValue(value, "Total");
                ReportPropertyChanged("Total");
                OnTotalChanged();
            }
        }
        private global::System.Decimal _Total;
        partial void OnTotalChanging(global::System.Decimal value);
        partial void OnTotalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AdventureWorksModel", Name="vWorkOrderRouting")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vWorkOrderRouting : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vWorkOrderRouting object.
        /// </summary>
        /// <param name="workOrderID">Initial value of the WorkOrderID property.</param>
        /// <param name="productID">Initial value of the ProductID property.</param>
        /// <param name="productNumber">Initial value of the ProductNumber property.</param>
        /// <param name="productName">Initial value of the ProductName property.</param>
        /// <param name="operationSequence">Initial value of the OperationSequence property.</param>
        /// <param name="locationID">Initial value of the LocationID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="scheduledStartDate">Initial value of the ScheduledStartDate property.</param>
        /// <param name="scheduledEndDate">Initial value of the ScheduledEndDate property.</param>
        /// <param name="plannedCost">Initial value of the PlannedCost property.</param>
        /// <param name="orderQty">Initial value of the OrderQty property.</param>
        /// <param name="scrappedQty">Initial value of the ScrappedQty property.</param>
        /// <param name="dueDate">Initial value of the DueDate property.</param>
        /// <param name="id">Initial value of the ID property.</param>
        public static vWorkOrderRouting CreatevWorkOrderRouting(global::System.Int32 workOrderID, global::System.Int32 productID, global::System.String productNumber, global::System.String productName, global::System.Int16 operationSequence, global::System.Int16 locationID, global::System.String name, global::System.DateTime scheduledStartDate, global::System.DateTime scheduledEndDate, global::System.Decimal plannedCost, global::System.Int32 orderQty, global::System.Int16 scrappedQty, global::System.DateTime dueDate, global::System.Int64 id)
        {
            vWorkOrderRouting vWorkOrderRouting = new vWorkOrderRouting();
            vWorkOrderRouting.WorkOrderID = workOrderID;
            vWorkOrderRouting.ProductID = productID;
            vWorkOrderRouting.ProductNumber = productNumber;
            vWorkOrderRouting.ProductName = productName;
            vWorkOrderRouting.OperationSequence = operationSequence;
            vWorkOrderRouting.LocationID = locationID;
            vWorkOrderRouting.Name = name;
            vWorkOrderRouting.ScheduledStartDate = scheduledStartDate;
            vWorkOrderRouting.ScheduledEndDate = scheduledEndDate;
            vWorkOrderRouting.PlannedCost = plannedCost;
            vWorkOrderRouting.OrderQty = orderQty;
            vWorkOrderRouting.ScrappedQty = scrappedQty;
            vWorkOrderRouting.DueDate = dueDate;
            vWorkOrderRouting.ID = id;
            return vWorkOrderRouting;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 WorkOrderID
        {
            get
            {
                return _WorkOrderID;
            }
            set
            {
                OnWorkOrderIDChanging(value);
                ReportPropertyChanging("WorkOrderID");
                _WorkOrderID = StructuralObject.SetValidValue(value, "WorkOrderID");
                ReportPropertyChanged("WorkOrderID");
                OnWorkOrderIDChanged();
            }
        }
        private global::System.Int32 _WorkOrderID;
        partial void OnWorkOrderIDChanging(global::System.Int32 value);
        partial void OnWorkOrderIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProductID
        {
            get
            {
                return _ProductID;
            }
            set
            {
                OnProductIDChanging(value);
                ReportPropertyChanging("ProductID");
                _ProductID = StructuralObject.SetValidValue(value, "ProductID");
                ReportPropertyChanged("ProductID");
                OnProductIDChanged();
            }
        }
        private global::System.Int32 _ProductID;
        partial void OnProductIDChanging(global::System.Int32 value);
        partial void OnProductIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProductNumber
        {
            get
            {
                return _ProductNumber;
            }
            set
            {
                OnProductNumberChanging(value);
                ReportPropertyChanging("ProductNumber");
                _ProductNumber = StructuralObject.SetValidValue(value, false, "ProductNumber");
                ReportPropertyChanged("ProductNumber");
                OnProductNumberChanged();
            }
        }
        private global::System.String _ProductNumber;
        partial void OnProductNumberChanging(global::System.String value);
        partial void OnProductNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProductName
        {
            get
            {
                return _ProductName;
            }
            set
            {
                OnProductNameChanging(value);
                ReportPropertyChanging("ProductName");
                _ProductName = StructuralObject.SetValidValue(value, false, "ProductName");
                ReportPropertyChanged("ProductName");
                OnProductNameChanged();
            }
        }
        private global::System.String _ProductName;
        partial void OnProductNameChanging(global::System.String value);
        partial void OnProductNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 OperationSequence
        {
            get
            {
                return _OperationSequence;
            }
            set
            {
                OnOperationSequenceChanging(value);
                ReportPropertyChanging("OperationSequence");
                _OperationSequence = StructuralObject.SetValidValue(value, "OperationSequence");
                ReportPropertyChanged("OperationSequence");
                OnOperationSequenceChanged();
            }
        }
        private global::System.Int16 _OperationSequence;
        partial void OnOperationSequenceChanging(global::System.Int16 value);
        partial void OnOperationSequenceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 LocationID
        {
            get
            {
                return _LocationID;
            }
            set
            {
                OnLocationIDChanging(value);
                ReportPropertyChanging("LocationID");
                _LocationID = StructuralObject.SetValidValue(value, "LocationID");
                ReportPropertyChanged("LocationID");
                OnLocationIDChanged();
            }
        }
        private global::System.Int16 _LocationID;
        partial void OnLocationIDChanging(global::System.Int16 value);
        partial void OnLocationIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ScheduledStartDate
        {
            get
            {
                return _ScheduledStartDate;
            }
            set
            {
                OnScheduledStartDateChanging(value);
                ReportPropertyChanging("ScheduledStartDate");
                _ScheduledStartDate = StructuralObject.SetValidValue(value, "ScheduledStartDate");
                ReportPropertyChanged("ScheduledStartDate");
                OnScheduledStartDateChanged();
            }
        }
        private global::System.DateTime _ScheduledStartDate;
        partial void OnScheduledStartDateChanging(global::System.DateTime value);
        partial void OnScheduledStartDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ActualStartDate
        {
            get
            {
                return _ActualStartDate;
            }
            set
            {
                OnActualStartDateChanging(value);
                ReportPropertyChanging("ActualStartDate");
                _ActualStartDate = StructuralObject.SetValidValue(value, "ActualStartDate");
                ReportPropertyChanged("ActualStartDate");
                OnActualStartDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ActualStartDate;
        partial void OnActualStartDateChanging(Nullable<global::System.DateTime> value);
        partial void OnActualStartDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ScheduledEndDate
        {
            get
            {
                return _ScheduledEndDate;
            }
            set
            {
                OnScheduledEndDateChanging(value);
                ReportPropertyChanging("ScheduledEndDate");
                _ScheduledEndDate = StructuralObject.SetValidValue(value, "ScheduledEndDate");
                ReportPropertyChanged("ScheduledEndDate");
                OnScheduledEndDateChanged();
            }
        }
        private global::System.DateTime _ScheduledEndDate;
        partial void OnScheduledEndDateChanging(global::System.DateTime value);
        partial void OnScheduledEndDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ActualEndDate
        {
            get
            {
                return _ActualEndDate;
            }
            set
            {
                OnActualEndDateChanging(value);
                ReportPropertyChanging("ActualEndDate");
                _ActualEndDate = StructuralObject.SetValidValue(value, "ActualEndDate");
                ReportPropertyChanged("ActualEndDate");
                OnActualEndDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ActualEndDate;
        partial void OnActualEndDateChanging(Nullable<global::System.DateTime> value);
        partial void OnActualEndDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ActualResourceHrs
        {
            get
            {
                return _ActualResourceHrs;
            }
            set
            {
                OnActualResourceHrsChanging(value);
                ReportPropertyChanging("ActualResourceHrs");
                _ActualResourceHrs = StructuralObject.SetValidValue(value, "ActualResourceHrs");
                ReportPropertyChanged("ActualResourceHrs");
                OnActualResourceHrsChanged();
            }
        }
        private Nullable<global::System.Decimal> _ActualResourceHrs;
        partial void OnActualResourceHrsChanging(Nullable<global::System.Decimal> value);
        partial void OnActualResourceHrsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal PlannedCost
        {
            get
            {
                return _PlannedCost;
            }
            set
            {
                OnPlannedCostChanging(value);
                ReportPropertyChanging("PlannedCost");
                _PlannedCost = StructuralObject.SetValidValue(value, "PlannedCost");
                ReportPropertyChanged("PlannedCost");
                OnPlannedCostChanged();
            }
        }
        private global::System.Decimal _PlannedCost;
        partial void OnPlannedCostChanging(global::System.Decimal value);
        partial void OnPlannedCostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ActualCost
        {
            get
            {
                return _ActualCost;
            }
            set
            {
                OnActualCostChanging(value);
                ReportPropertyChanging("ActualCost");
                _ActualCost = StructuralObject.SetValidValue(value, "ActualCost");
                ReportPropertyChanged("ActualCost");
                OnActualCostChanged();
            }
        }
        private Nullable<global::System.Decimal> _ActualCost;
        partial void OnActualCostChanging(Nullable<global::System.Decimal> value);
        partial void OnActualCostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrderQty
        {
            get
            {
                return _OrderQty;
            }
            set
            {
                OnOrderQtyChanging(value);
                ReportPropertyChanging("OrderQty");
                _OrderQty = StructuralObject.SetValidValue(value, "OrderQty");
                ReportPropertyChanged("OrderQty");
                OnOrderQtyChanged();
            }
        }
        private global::System.Int32 _OrderQty;
        partial void OnOrderQtyChanging(global::System.Int32 value);
        partial void OnOrderQtyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 ScrappedQty
        {
            get
            {
                return _ScrappedQty;
            }
            set
            {
                OnScrappedQtyChanging(value);
                ReportPropertyChanging("ScrappedQty");
                _ScrappedQty = StructuralObject.SetValidValue(value, "ScrappedQty");
                ReportPropertyChanged("ScrappedQty");
                OnScrappedQtyChanged();
            }
        }
        private global::System.Int16 _ScrappedQty;
        partial void OnScrappedQtyChanging(global::System.Int16 value);
        partial void OnScrappedQtyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DueDate
        {
            get
            {
                return _DueDate;
            }
            set
            {
                OnDueDateChanging(value);
                ReportPropertyChanging("DueDate");
                _DueDate = StructuralObject.SetValidValue(value, "DueDate");
                ReportPropertyChanged("DueDate");
                OnDueDateChanged();
            }
        }
        private global::System.DateTime _DueDate;
        partial void OnDueDateChanging(global::System.DateTime value);
        partial void OnDueDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> ScrapReasonID
        {
            get
            {
                return _ScrapReasonID;
            }
            set
            {
                OnScrapReasonIDChanging(value);
                ReportPropertyChanging("ScrapReasonID");
                _ScrapReasonID = StructuralObject.SetValidValue(value, "ScrapReasonID");
                ReportPropertyChanged("ScrapReasonID");
                OnScrapReasonIDChanged();
            }
        }
        private Nullable<global::System.Int16> _ScrapReasonID;
        partial void OnScrapReasonIDChanging(Nullable<global::System.Int16> value);
        partial void OnScrapReasonIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ScrapReason
        {
            get
            {
                return _ScrapReason;
            }
            set
            {
                OnScrapReasonChanging(value);
                ReportPropertyChanging("ScrapReason");
                _ScrapReason = StructuralObject.SetValidValue(value, true, "ScrapReason");
                ReportPropertyChanged("ScrapReason");
                OnScrapReasonChanged();
            }
        }
        private global::System.String _ScrapReason;
        partial void OnScrapReasonChanging(global::System.String value);
        partial void OnScrapReasonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();

        #endregion

    }

    #endregion

}
