<?xml version="1.0" encoding="utf-8"?>
<Database Name="SlickTicket" Class="dbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=SlickTicket;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SlickTicket" Provider="System.Data.SqlClient" />
  <Table Name="dbo.allowed_email_domains" Member="allowed_email_domains">
    <Type Name="allowed_email_domain">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="domain" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.users" Member="users">
    <Type Name="user">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userName" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="phone" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="sub_unit" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="is_admin" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="user_ticket" Member="tickets" ThisKey="id" OtherKey="submitter" Type="ticket" />
      <Association Name="user_comment" Member="comments" ThisKey="id" OtherKey="submitter" Type="comment" />
      <Association Name="sub_unit_user" Member="sub_unit1" ThisKey="sub_unit" OtherKey="id" Type="sub_unit" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.attachments" Member="attachments">
    <Type Name="attachment">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ticket_ref" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="comment_ref" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="attachment_name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="attachment_size" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="submitted" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="ticket_attachment" Member="ticket" ThisKey="ticket_ref" OtherKey="id" Type="ticket" IsForeignKey="true" />
      <Association Name="comment_attachment" Member="comment" ThisKey="comment_ref" OtherKey="id" Type="comment" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.faq" Member="faqs">
    <Type Name="faq">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="body" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.priority" Member="priorities">
    <Type Name="priority">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="priority_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[level]" Member="level" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="priority_ticket" Member="tickets" ThisKey="id" OtherKey="priority" Type="ticket" />
      <Association Name="priority_comment" Member="comments" ThisKey="id" OtherKey="priority_id" Type="comment" />
    </Type>
  </Table>
  <Table Name="dbo.security_levels" Member="security_levels">
    <Type Name="security_level">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="security_level_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="security_level_description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="security_level_sub_unit" Member="sub_units" ThisKey="id" OtherKey="access_level" Type="sub_unit" />
      <Association Name="security_level_user_group" Member="user_groups" ThisKey="id" OtherKey="security_level" Type="user_group" />
    </Type>
  </Table>
  <Table Name="dbo.statuses" Member="statuses">
    <Type Name="statuse">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="status_order" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="status_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="statuse_ticket" Member="tickets" ThisKey="id" OtherKey="ticket_status" Type="ticket" />
      <Association Name="statuse_comment" Member="comments" ThisKey="id" OtherKey="status_id" Type="comment" />
    </Type>
  </Table>
  <Table Name="dbo.styles" Member="styles">
    <Type Name="style">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="style_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="text_color" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="borders" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="body" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="links" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="hover" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="button_text" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="header" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="alt_rows" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="background" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.sub_units" Member="sub_units">
    <Type Name="sub_unit">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="unit_ref" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sub_unit_name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="access_level" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="mailto" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="sub_unit_user" Member="users" ThisKey="id" OtherKey="sub_unit" Type="user" />
      <Association Name="sub_unit_ticket" Member="tickets" ThisKey="id" OtherKey="assigned_to_group" Type="ticket" />
      <Association Name="sub_unit_ticket1" Member="tickets1" ThisKey="id" OtherKey="assigned_to_group_last" Type="ticket" />
      <Association Name="sub_unit_ticket2" Member="tickets2" ThisKey="id" OtherKey="originating_group" Type="ticket" />
      <Association Name="sub_unit_comment" Member="comments" ThisKey="id" OtherKey="assigned_to" Type="comment" />
      <Association Name="security_level_sub_unit" Member="security_level" ThisKey="access_level" OtherKey="id" Type="security_level" IsForeignKey="true" />
      <Association Name="unit_sub_unit" Member="unit" ThisKey="unit_ref" OtherKey="id" Type="unit" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tickets" Member="tickets">
    <Type Name="ticket">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="details" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="submitter" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="submitted" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="last_action" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="closed" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="assigned_to_group" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="assigned_to_group_last" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ticket_status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="priority" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="originating_group" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ticket_attachment" Member="attachments" ThisKey="id" OtherKey="ticket_ref" Type="attachment" />
      <Association Name="ticket_comment" Member="comments" ThisKey="id" OtherKey="ticket_ref" Type="comment" />
      <Association Name="sub_unit_ticket" Member="sub_unit" ThisKey="assigned_to_group" OtherKey="id" Type="sub_unit" IsForeignKey="true" />
      <Association Name="sub_unit_ticket1" Member="sub_unit1" ThisKey="assigned_to_group_last" OtherKey="id" Type="sub_unit" IsForeignKey="true" />
      <Association Name="sub_unit_ticket2" Member="sub_unit2" ThisKey="originating_group" OtherKey="id" Type="sub_unit" IsForeignKey="true" />
      <Association Name="priority_ticket" Member="priority1" ThisKey="priority" OtherKey="id" Type="priority" IsForeignKey="true" />
      <Association Name="user_ticket" Member="user" ThisKey="submitter" OtherKey="id" Type="user" IsForeignKey="true" />
      <Association Name="statuse_ticket" Member="statuse" ThisKey="ticket_status" OtherKey="id" Type="statuse" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.units" Member="units">
    <Type Name="unit">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="unit_name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="unit_sub_unit" Member="sub_units" ThisKey="id" OtherKey="unit_ref" Type="sub_unit" />
    </Type>
  </Table>
  <Table Name="dbo.user_groups" Member="user_groups">
    <Type Name="user_group">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ad_group" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="security_level" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="security_level_user_group" Member="security_level1" ThisKey="security_level" OtherKey="id" Type="security_level" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.comments" Member="comments">
    <Type Name="comment">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="comment" Member="comment1" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ticket_ref" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="submitter" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="submitted" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="assigned_to" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="priority_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="status_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="comment_attachment" Member="attachments" ThisKey="id" OtherKey="comment_ref" Type="attachment" />
      <Association Name="sub_unit_comment" Member="sub_unit" ThisKey="assigned_to" OtherKey="id" Type="sub_unit" IsForeignKey="true" />
      <Association Name="priority_comment" Member="priority" ThisKey="priority_id" OtherKey="id" Type="priority" IsForeignKey="true" />
      <Association Name="statuse_comment" Member="statuse" ThisKey="status_id" OtherKey="id" Type="statuse" IsForeignKey="true" />
      <Association Name="user_comment" Member="user" ThisKey="submitter" OtherKey="id" Type="user" IsForeignKey="true" />
      <Association Name="ticket_comment" Member="ticket" ThisKey="ticket_ref" OtherKey="id" Type="ticket" IsForeignKey="true" />
    </Type>
  </Table>
</Database>