#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3625
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFToDB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="PracDB")]
	public partial class LinqPracDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertt1(t1 instance);
    partial void Updatet1(t1 instance);
    partial void Deletet1(t1 instance);
    #endregion
		
		public LinqPracDBDataContext() : 
				base(global::WCFToDB.Properties.Settings.Default.PracDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LinqPracDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqPracDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqPracDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqPracDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<t1> t1s
		{
			get
			{
				return this.GetTable<t1>();
			}
		}
		
		public System.Data.Linq.Table<EmployeeTable> EmployeeTables
		{
			get
			{
				return this.GetTable<EmployeeTable>();
			}
		}
	}
	
	[Table(Name="dbo.t1")]
	public partial class t1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _t1id;
		
		private string _firstName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ont1idChanging(int value);
    partial void Ont1idChanged();
    partial void OnfirstNameChanging(string value);
    partial void OnfirstNameChanged();
    #endregion
		
		public t1()
		{
			OnCreated();
		}
		
		[Column(Storage="_t1id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int t1id
		{
			get
			{
				return this._t1id;
			}
			set
			{
				if ((this._t1id != value))
				{
					this.Ont1idChanging(value);
					this.SendPropertyChanging();
					this._t1id = value;
					this.SendPropertyChanged("t1id");
					this.Ont1idChanged();
				}
			}
		}
		
		[Column(Storage="_firstName", DbType="VarChar(20)")]
		public string firstName
		{
			get
			{
				return this._firstName;
			}
			set
			{
				if ((this._firstName != value))
				{
					this.OnfirstNameChanging(value);
					this.SendPropertyChanging();
					this._firstName = value;
					this.SendPropertyChanged("firstName");
					this.OnfirstNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.EmployeeTable")]
	public partial class EmployeeTable
	{
		
		private int _Employeeid;
		
		private string _LoginID;
		
		private string _Title;
		
		private System.DateTime _BirthDate;
		
		public EmployeeTable()
		{
		}
		
		[Column(Storage="_Employeeid", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Employeeid
		{
			get
			{
				return this._Employeeid;
			}
			set
			{
				if ((this._Employeeid != value))
				{
					this._Employeeid = value;
				}
			}
		}
		
		[Column(Storage="_LoginID", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string LoginID
		{
			get
			{
				return this._LoginID;
			}
			set
			{
				if ((this._LoginID != value))
				{
					this._LoginID = value;
				}
			}
		}
		
		[Column(Storage="_Title", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[Column(Storage="_BirthDate", DbType="DateTime NOT NULL")]
		public System.DateTime BirthDate
		{
			get
			{
				return this._BirthDate;
			}
			set
			{
				if ((this._BirthDate != value))
				{
					this._BirthDate = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
