//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomAuthenticationClient.CustAuthenticationServiceClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustAuthenticationServiceClient.ICustomAuthenticationService")]
    public interface ICustomAuthenticationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomAuthenticationService/GetData", ReplyAction="http://tempuri.org/ICustomAuthenticationService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomAuthenticationService/GetData", ReplyAction="http://tempuri.org/ICustomAuthenticationService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomAuthenticationService/GetClaims", ReplyAction="http://tempuri.org/ICustomAuthenticationService/GetClaimsResponse")]
        System.Collections.Generic.List<string> GetClaims();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomAuthenticationService/GetClaims", ReplyAction="http://tempuri.org/ICustomAuthenticationService/GetClaimsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetClaimsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomAuthenticationServiceChannel : CustomAuthenticationClient.CustAuthenticationServiceClient.ICustomAuthenticationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomAuthenticationServiceClient : System.ServiceModel.ClientBase<CustomAuthenticationClient.CustAuthenticationServiceClient.ICustomAuthenticationService>, CustomAuthenticationClient.CustAuthenticationServiceClient.ICustomAuthenticationService {
        
        public CustomAuthenticationServiceClient() {
        }
        
        public CustomAuthenticationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomAuthenticationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomAuthenticationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomAuthenticationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public System.Collections.Generic.List<string> GetClaims() {
            return base.Channel.GetClaims();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetClaimsAsync() {
            return base.Channel.GetClaimsAsync();
        }
    }
}
