//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace ETFramework
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class EDM_EmployeeContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new EDM_EmployeeContainer object using the connection string found in the 'EDM_EmployeeContainer' section of the application configuration file.
        /// </summary>
        public EDM_EmployeeContainer() : base("name=EDM_EmployeeContainer", "EDM_EmployeeContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EDM_EmployeeContainer object.
        /// </summary>
        public EDM_EmployeeContainer(string connectionString) : base(connectionString, "EDM_EmployeeContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EDM_EmployeeContainer object.
        /// </summary>
        public EDM_EmployeeContainer(EntityConnection connection) : base(connection, "EDM_EmployeeContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
    }
    

    #endregion
    
    
}
