//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Switch
{
	public virtual ICommand ICommand
	{
		get;
		set;
	}

	public virtual void ExecuteCommand()
	{
		throw new System.NotImplementedException();
	}

	public virtual void AddCommand(object ICommand)
	{
		throw new System.NotImplementedException();
	}

}

