CREATE TABLE [dbo].[HR_CMP_AS_WorkShifts](
	[CompanyID] [bigint] IDENTITY(1,1) NOT NULL,
	[WorkShiftID] [int] NOT NULL,
	[StationID] [int] NOT NULL,
 CONSTRAINT [PK_HR_CMP_AS_WorkShifts] PRIMARY KEY CLUSTERED 
(
	[CompanyID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
)


