CREATE TABLE [dbo].[HR_CMP_AccountsWithBanks](
	[CompanyID] [bigint] NOT NULL,
	[BankID] [int] NOT NULL,
 CONSTRAINT [PK_HR_CMP_AccountsWithBanks] PRIMARY KEY CLUSTERED 
(
	[CompanyID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
)


