CREATE TABLE [dbo].[HR_GLB_LKP_NameTitle](
	[TitleCode] [int] IDENTITY(1,1) NOT NULL,
	[TitleName] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
 CONSTRAINT [PK_HR_GLB_LKP_NameTitle] PRIMARY KEY CLUSTERED 
(
	[TitleCode] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
)


