CREATE TABLE [dbo].[HR_LKP_BankAccountTypes](
	[BankTypeID] [int] IDENTITY(1,1) NOT NULL,
	[BankAccountType] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
 CONSTRAINT [PK_HR_LKP_BankAccountTypes] PRIMARY KEY CLUSTERED 
(
	[BankTypeID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
)


