//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3625
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://service", ConfigurationName="ICalculator", CallbackContract=typeof(ICalculatorCallback))]
public interface ICalculator
{
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://service/ICalculator/Clear")]
    void Clear();
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://service/ICalculator/AddTo")]
    void AddTo(double n);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://service/ICalculator/SubtractTo")]
    void SubtractTo(double n);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://service/ICalculator/MultipleTo")]
    void MultipleTo(double n);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://service/ICalculator/DivideTo")]
    void DivideTo(double n);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface ICalculatorCallback
{
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://service/ICalculator/Result")]
    void Result(double n);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://service/ICalculator/Equation")]
    void Equation(string str);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface ICalculatorChannel : ICalculator, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class CalculatorClient : System.ServiceModel.DuplexClientBase<ICalculator>, ICalculator
{
    
    public CalculatorClient(System.ServiceModel.InstanceContext callbackInstance) : 
            base(callbackInstance)
    {
    }
    
    public CalculatorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
            base(callbackInstance, endpointConfigurationName)
    {
    }
    
    public CalculatorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
            base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }
    
    public CalculatorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }
    
    public CalculatorClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(callbackInstance, binding, remoteAddress)
    {
    }
    
    public void Clear()
    {
        base.Channel.Clear();
    }
    
    public void AddTo(double n)
    {
        base.Channel.AddTo(n);
    }
    
    public void SubtractTo(double n)
    {
        base.Channel.SubtractTo(n);
    }
    
    public void MultipleTo(double n)
    {
        base.Channel.MultipleTo(n);
    }
    
    public void DivideTo(double n)
    {
        base.Channel.DivideTo(n);
    }
}
